### ISSUE TITLE
Artwork Flappy Duck

### ISSUE THREAD

**Issue by franklin190** [marczobec/spinning-shots#2]

**Comment by marczobec** [comment]
Hi Franklin,

are you mixing something up? This is the repo for Spinning Shots and I don’t have/know another repo called Flappy Duck.


On 21 November 2015 at 15:32:24, franklin190 (notifications@github.com) wrote:

I'm new at programming and I cannot photoshop at all...

I really like the artwork you made for Flappy Duck!
Can I use it for free in my app?

Thank you in advance!

**Comment by franklin190** [comment]
I'm sorry!
Wrong repo!
